parameters:
  # - name: dependsOn
  #   type: string
  - name: dependsOn
    type: object
  - name: environmentName
    type: string
  # - name: deployBranch
  #   type: string

stages:
  # - ${{ if and(eq(variables['Build.SourceBranch'], 'refs/heads/${{ parameters.deployBranch }}'), ne(variables['Build.Reason'], 'PullRequest')) }}:
    - stage: Build_${{ parameters.environmentName }}
      dependsOn: ${{parameters.dependsOn }}
      jobs:
        - job: Build_${{ parameters.environmentName }}
          displayName: Build for ${{ parameters.environmentName }}
          # pool:
          #   vmImage: $(vmImageName)
          steps:
            - script: |
                echo "image pull secret is ${{ parameters.environmentName }} files"
                echo "image repo is ${{ parameters.environmentName }} files"
                echo "docker file path is ${{ parameters.environmentName }} files"
                echo "docker registry sc is ${{ parameters.environmentName }} files"
                echo "tag is ${{ parameters.environmentName }} files"
                echo "trivy version is ${{ parameters.environmentName }} files"
                echo "container registry is ${{ parameters.environmentName }} files"
                echo "kubernetes name space is ${{ parameters.environmentName }} files"
                echo "kubernetes sc endpoint is ${{ parameters.environmentName }} files"
              displayName: building the ${{ parameters.environmentName }} files
